### ISSUE TITLE
Remove duplicate double quotes from strings

### ISSUE THREAD

**Issue by SteffanDonal** [nchristopher/quoter#74]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just polish.

**Describe the solution you'd like**
New and existing quote content should have surrounding quotes removed.

**Describe alternatives you've considered**
Editing a library of server quotes is ... painful and long

**Comment by nchristopher** [comment]
I can remove quotes from new strings, but removing them from existing strings could be tricky. I'd either have to remove the quotes whenever a quote is displayed - but I don't want to have "legacy" support - or update all existing quotes in the database - but I'm not sure how to do that.
