### ISSUE TITLE
/inspire doesn't render emoji (unicode?) characters properly

### ISSUE THREAD

**Issue by Ybalrid** [nchristopher/quoter#94]
**Describe the bug**

When `/inspire` select a quote containing an emoji, it gets rendered as a block with the codepoint number instead.

**To Reproduce**

(See attached image)

Generate an image with a quote containing an emoji

**Expected behavior**

It should read `"Lawyers! 🙄"`  in the screenshot below:

**Screenshots**

![image](https://user-images.githubusercontent.com/1816251/145615786-4f4918ec-b6a3-4f17-bbd1-3280f7fe726e.png)

**Comment by nchristopher** [comment]
So I... kind of got it to work? The emojis render without color, which isn't good. I'm not experienced with canvas, @Neesh774 implemented it, so I'm hoping he can figure out what's going on.

![Output image of `/inspire`, emojis rendered without color](https://i.imgur.com/R5wHfDh.png)

**Comment by Ybalrid** [comment]
May I suggest rendering them with the Twemoji font? It's open-source and the one used in Discord. They will *perfectly* blend in (and are amongst the best-looking emojis around IMHO)

https://twemoji.twitter.com/

Also, it would probably be worthwhile to check what is happening with non-English characters set in text... Can the bot render an image containing something like this : `日本語が話せなくてごめんなさい。`* ? As I don't know if the bug is "It doesn't render Emoji" or is a wider "It doesn't render Unicode characters" issue

(*this just reads "I'm sorry I don't speak Japanese")

**Comment by nchristopher** [comment]
I'm not sure why, but this bug is fixed now. The emojis render in black and white (default glyphs), but I personally think it fits in better than Twemoji.
